version: '3'

services:
  client:
    image: client:latest
    ports:
      - "3000:3000"
    networks:
      - mynetwork
    depends_on:
      - server

  server:
    image: server:latest
    ports:
      - "5000:5000"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
